### ISSUE TITLE
Separate document root

### ISSUE THREAD

**Issue by szepeviktor** [nexcess/wp-git-repo-starter#1]
Please add a separate document root that will be publicly accessible.
It can be called `public`.

Even cPanel-driven shared hosting spaces can have a custom document root!

**Comment by stevegrunwell** [comment]
This repository is meant to be more of a "this is what a basic WordPress repo might look like" example; moving the document root (or adding a secondary document root) would likely be outside the scope of the audience using this repo. I appreciate the suggestion, however, thank you! 😄

**Comment by szepeviktor** [comment]
Okay-okay.
